# Generated by Django 2.2.4 on 2019-11-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('duration', models.DurationField()),
                ('url', models.URLField()),
                ('thumbnail', models.TextField()),
            ],
        ),
    ]
